import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {MapContainer, TileLayer, CircleMarker, Polygon, Polyline, Popup} from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import './styles.css';
import './enhancements.css';

const API = import.meta.env.VITE_API_BASE_URL || '/api';
const empty = {rainfall: [], terrain: [], predictions: [], alerts: [], segments: [], nodes: [], simulation: {rainfallIntensity: 40.3}};
const colors = {LOW:'#39d98a', MODERATE:'#f8cc5d', HIGH:'#ff963c', SEVERE:'#f35b66'};
const networkColors = {NORMAL:'#3d9bff', WARNING:'#f8cc5d', CRITICAL:'#ff963c', OVERFLOW:'#f35b66'};
const horizons = [{key:'CURRENT', label:'CURRENT', data:'CURRENT'}, {key:'30',label:'30 MIN',data:'30 minutes'}, {key:'60',label:'1 HOUR',data:'60 minutes'}, {key:'120',label:'2 HOURS',data:'120 minutes'}, {key:'180',label:'3 HOURS',data:'180 minutes'}];
const scenarios = [{name:'Normal',value:15,detail:'Low rainfall'},{name:'Baseline',value:40.3,detail:'Demo default'},{name:'Heavy',value:70,detail:'High runoff'},{name:'Extreme',value:95,detail:'Overflow test'}];

function Badge({level}) { return <span className="badge" style={{background:colors[level] || networkColors[level] || '#60708d'}}>{level}</span>; }
function Metric({label,value,sub,accent='blue'}) { return <article className={`metric ${accent}`}><span>{label}</span><strong>{value}</strong><small>{sub}</small></article>; }
function LoadBar({value}) { return <span className="load"><i style={{width:`${Math.min(100,value)}%`}} /></span>; }
function statusFromSegment(s) { const ratio=s.currentFlow/s.capacity; return ratio>1?'OVERFLOW':ratio>.85?'CRITICAL':ratio>.7?'WARNING':'NORMAL'; }
function riskPolygon(p) { const d=.006+p.riskScore/14500; return [[p.latitude+d,p.longitude-d],[p.latitude+d*.7,p.longitude+d],[p.latitude-d,p.longitude+d*1.15],[p.latitude-d*.8,p.longitude-d*.8]]; }
function ForecastControls({horizon,setHorizon}) { return <div className="forecast-controls">{horizons.map(h=><button key={h.key} className={horizon===h.data?'active':''} onClick={()=>setHorizon(h.data)}>{h.label}</button>)}</div>; }
function LayerToggles({layers,setLayers}) { return <div className="layer-toggles">{[['rainfall','🌧 Rainfall'],['risk','Flood Risk Zones'],['network','Drainage Network'],['critical','⚠ Critical Points']].map(([key,label])=><label key={key}><input type="checkbox" checked={layers[key]} onChange={e=>setLayers({...layers,[key]:e.target.checked})}/>{label}</label>)}</div>; }

function PuneMap({predictions,segments,nodes,horizon,layers,route}) {
  const forecast=predictions.filter(p=>p.horizon===(horizon==='CURRENT'?'30 minutes':horizon)); const nodeById=Object.fromEntries(nodes.map(n=>[n.id,n]));
  const routeCoords=route?.route?.length ? [[18.5074,73.8077],[18.520,73.824],[18.531,73.847],[18.553,73.878]] : [];
  return <div className="map-wrap"><MapContainer center={[18.5204,73.8567]} zoom={12} scrollWheelZoom={false}><TileLayer attribution="© OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>
    {layers.risk && forecast.map(p=><Polygon key={p.location} positions={riskPolygon(p)} pathOptions={{color:colors[p.riskLevel],fillColor:colors[p.riskLevel],fillOpacity:.22,weight:2}}><Popup><b>Flood Risk Zone · {p.location}</b><br/>Risk: {p.riskLevel} ({p.riskScore})<br/>Predicted depth: {p.waterDepthCm} cm</Popup></Polygon>)}
    {layers.rainfall && forecast.map(p=><CircleMarker key={`rain-${p.location}`} center={[p.latitude,p.longitude]} radius={5} pathOptions={{color:'#4db5ff',fillColor:'#4db5ff',fillOpacity:.9}}><Popup><b>🌧 Rainfall point · {p.location}</b><br/>Prototype rainfall coupled to this forecast.</Popup></CircleMarker>)}
    {layers.network && segments.map(s=>{const a=nodeById[s.sourceNode],b=nodeById[s.destinationNode]; if(!a||!b)return null;const status=statusFromSegment(s); return <Polyline key={s.id} positions={[[a.latitude,a.longitude],[b.latitude,b.longitude]]} pathOptions={{color:networkColors[status],weight:5,opacity:.9}}><Popup><b>Drainage segment · {s.name}</b><br/>Load: {Math.round(s.currentFlow/s.capacity*100)}%<br/>Status: {status}</Popup></Polyline>;})}
    {layers.critical && forecast.filter(p=>p.riskLevel==='HIGH'||p.riskLevel==='SEVERE').map(p=><CircleMarker key={`critical-${p.location}`} center={[p.latitude+.002,p.longitude+.002]} radius={9} pathOptions={{color:'#fff',fillColor:colors[p.riskLevel],fillOpacity:1,weight:2}}><Popup><b>🚨 Flood incident · {p.location}</b><br/>Rainfall: prototype simulated<br/>Drainage load: {Math.max(...segments.map(s=>Math.round(s.currentFlow/s.capacity*100)))}%<br/>Overflow probability: {p.overflowProbability}%<br/>Predicted water depth: {p.waterDepthCm} cm<br/>Flood risk: {p.riskLevel}</Popup></CircleMarker>)}
    {routeCoords.length>0 && <><Polyline positions={routeCoords} pathOptions={{color:'#42df8d',weight:6,opacity:.9}}/><CircleMarker center={routeCoords[0]} radius={8} pathOptions={{color:'#fff',fillColor:'#42df8d',fillOpacity:1}}><Popup>📍 Source</Popup></CircleMarker><CircleMarker center={routeCoords.at(-1)} radius={8} pathOptions={{color:'#fff',fillColor:'#f35b66',fillOpacity:1}}><Popup>📍 Destination</Popup></CircleMarker></>}
  </MapContainer><div className="map-legend"><b>FLOOD RISK</b><span><i style={{background:colors.LOW}}/>Low</span><span><i style={{background:colors.MODERATE}}/>Moderate</span><span><i style={{background:colors.HIGH}}/>High</span><span><i style={{background:colors.SEVERE}}/>Severe</span><b>NETWORK STATUS</b><span><i style={{background:networkColors.NORMAL}}/>Normal</span><span><i style={{background:networkColors.WARNING}}/>Warning</span><span><i style={{background:networkColors.CRITICAL}}/>Critical</span><span><i style={{background:networkColors.OVERFLOW}}/>Overflow</span></div></div>;
}
function Pipeline({rainfall,terrain,segments,predictions}) { const rain=rainfall.reduce((sum,r)=>sum+r.rainfallIntensity,0)/(rainfall.length||1); const maxLoad=Math.max(0,...segments.map(s=>s.currentFlow/s.capacity*100)); const now=predictions.filter(p=>p.horizon==='60 minutes').sort((a,b)=>b.riskScore-a.riskScore)[0]; const terrainRisk=terrain.some(t=>t.historicalRisk>.7)?'Moderate':'Low'; const values=[['🌧','Rainfall Input',`${rain.toFixed(1)} mm/hr`],['⛰','Terrain Analysis',terrainRisk],['🤖','AI Runoff Prediction',`${Math.min(99,Math.round(rain*1.65))}%`],['🕳','Drainage Capacity',`${Math.round(maxLoad)}% load`],['💧','Hydraulic / Overflow',`${now?.overflowProbability||0}% probability`],['🚨','Flood Nowcasting',now?.riskLevel||'LOW']]; return <section className="pipeline panel"><div className="panel-head"><h2>Live Analysis Pipeline</h2><span>Rainfall → flood intelligence</span></div><div className="pipeline-flow">{values.map((v,i)=><React.Fragment key={v[1]}><div className="pipe-stage"><i>{v[0]}</i><span>{v[1]}</span><b className={v[2]==='SEVERE'?'danger':''}>{v[2]}</b></div>{i<values.length-1&&<em>→</em>}</React.Fragment>)}</div></section>; }
function Alerts({alerts}) { return <div className="alerts">{alerts.length?alerts.map(a=><article key={a.id}><Badge level={a.severity}/><div><b>{a.location} · {a.horizon}</b><p>{a.message}</p><small>Depth: {a.waterDepthCm} cm · <strong>Action:</strong> {a.recommendedAction}</small></div></article>):<p className="empty">No active forecast alerts.</p>}</div>; }
function RainTrend({series}) { const palette=['#4db5ff','#f35b66','#ff963c','#b987ff','#39d98a']; const max=Math.max(60,...series.flatMap(s=>s.points)); const coords=points=>points.map((p,i)=>`${52+i*112},${176-p/max*132}`).join(' '); return <div className="line-chart"><svg viewBox="0 0 650 210" role="img" aria-label="Six-hour prototype rainfall intensity trend"><g className="chart-grid">{[44,88,132,176].map(y=><line key={y} x1="52" x2="620" y1={y} y2={y}/>)}</g><text x="8" y="48">{max}</text><text x="13" y="136">{Math.round(max/2)}</text><text x="24" y="179">0</text>{series.map((s,i)=><polyline key={s.name} points={coords(s.points)} fill="none" stroke={palette[i]} strokeWidth="3" strokeLinejoin="round"/>) }{[0,1,2,3,4,5].map(i=><text key={i} x={47+i*112} y="202">{i===5?'Now':`${5-i}h`}</text>)}</svg><div className="chart-legend">{series.map((s,i)=><span key={s.name}><i style={{background:palette[i]}}/>{s.name}</span>)}</div></div>; }
function Rainfall({readings}) { const areas=['Yerawada','Hadapsar','Shivajinagar','Kothrud','Katraj']; const byName=Object.fromEntries(readings.map(r=>[r.location,r])); const trend=areas.map((name,i)=>({name,points:Array.from({length:6},(_,h)=>Math.max(4,Math.round((byName[name]?.rainfallIntensity||15)*(0.45+h*.11+(i%2)*.03))))})); return <section className="stack"><div className="summary-grid">{areas.map(a=>{let r=byName[a];let v=r?.rainfallIntensity||0;return <Metric key={a} label={a} value={`${v} mm/h`} sub={v>60?'EXTREME':v>40?'HEAVY':v>20?'MODERATE':'LOW'} accent={v>40?'red':v>20?'orange':'blue'}/>})}</div><section className="panel"><div className="panel-head"><h2>Last 6 Hours Rainfall Trend</h2><span>Prototype / simulated data</span></div><RainTrend series={trend}/></section><section className="panel"><div className="panel-head"><h2>Current rainfall intensity</h2><span>Prototype / simulated data</span></div><div className="rainbars">{readings.map(r=><div key={r.id}><strong>{r.rainfallIntensity}<small> mm/h</small></strong><i style={{height:`${Math.min(100,r.rainfallIntensity*1.7)}%`}}/><span>{r.location}</span></div>)}</div></section></section>; }
function Drainage({rows,full}) { const summary=rows.reduce((a,s)=>{a[statusFromSegment(s).toLowerCase()]++;return a;},{normal:0,warning:0,critical:0,overflow:0}); return <section className={`stack ${full?'full':''}`}><div className="summary-grid"><Metric label="Healthy Segments" value={summary.normal} sub="within capacity"/><Metric label="Warning Segments" value={summary.warning} sub="70–85% load" accent="yellow"/><Metric label="Critical Segments" value={summary.critical} sub="85–100% load" accent="orange"/><Metric label="Overflow Segments" value={summary.overflow} sub="above capacity" accent="red"/></div><section className="panel"><div className="panel-head"><h2>Drainage Network Health</h2><span>Hydraulic simulation</span></div><div className="network-strip">{rows.map(s=><div key={s.id}><span style={{background:networkColors[statusFromSegment(s)],width:`${Math.min(100,s.currentFlow/s.capacity*100)}%`}}/><b>{s.name}</b><small>{Math.round(s.currentFlow/s.capacity*100)}%</small></div>)}</div><div className="table-wrap"><table><thead><tr><th>Drainage Segment</th><th>Location</th><th>Current Load</th><th>Capacity</th><th>Status</th></tr></thead><tbody>{rows.map(s=>{let pct=Math.round(s.currentFlow/s.capacity*100);return <tr key={s.id}><td>{s.name}</td><td>{{'SC-01':'Shivajinagar','HC-07':'Hadapsar','YC-03':'Yerawada'}[s.name]}</td><td><LoadBar value={pct}/>{pct}%</td><td>100% ({s.capacity} m³/s)</td><td><Badge level={statusFromSegment(s)==='OVERFLOW'?'SEVERE':statusFromSegment(s)==='CRITICAL'?'HIGH':statusFromSegment(s)==='WARNING'?'MODERATE':'LOW'}/></td></tr>})}</tbody></table></div></section></section>; }
function Predictions({predictions,horizon,setHorizon,full}) { const [area,setArea]=useState('ALL'),[risk,setRisk]=useState('ALL'); const activeHorizon=horizon==='CURRENT'?'30 minutes':horizon; const rows=predictions.filter(p=>p.horizon===activeHorizon&&(area==='ALL'||p.location===area)&&(risk==='ALL'||p.riskLevel===risk)); const areas=[...new Set(predictions.map(p=>p.location))]; return <section className={`panel ${full?'full':''}`}><div className="panel-head"><h2>Flood Predictions</h2><span>Forecast generated using rainfall, terrain and drainage coupling.</span></div><div className="filters"><ForecastControls horizon={horizon} setHorizon={setHorizon}/><select value={area} onChange={e=>setArea(e.target.value)}><option>ALL</option>{areas.map(a=><option key={a}>{a}</option>)}</select><select value={risk} onChange={e=>setRisk(e.target.value)}><option>ALL</option>{Object.keys(colors).map(r=><option key={r}>{r}</option>)}</select></div><div className="table-wrap"><table><thead><tr><th>Area</th><th>Time Horizon</th><th>Risk Level</th><th>Risk Score</th><th>Predicted Water Depth</th><th>Overflow Probability</th></tr></thead><tbody>{rows.map((p,i)=><tr key={i}><td>{p.location}</td><td>{p.horizon}</td><td><Badge level={p.riskLevel}/></td><td>{p.riskScore}/100</td><td>{p.waterDepthCm} cm</td><td>{p.overflowProbability}%</td></tr>)}</tbody></table></div></section>; }
function RoutePlanner({data,horizon}) { const [source,setSource]=useState('Kothrud'),[destination,setDestination]=useState('Yerawada'),[route,setRoute]=useState(null); const plan=async e=>{e.preventDefault();const r=await fetch(`${API}/routes/safe`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source,destination})});setRoute(await r.json());}; return <section className="route"><div><p className="eyebrow">FLOOD-AWARE WEIGHTED ROUTING</p><h2>Plan a safer journey</h2><p className="route-copy">Route is calculated using flood-aware weighted routing.</p><form onSubmit={plan}><label>Source<input value={source} onChange={e=>setSource(e.target.value)}/></label><label>Destination<input value={destination} onChange={e=>setDestination(e.target.value)}/></label><button className="primary">Find safe route</button></form>{route&&<div className="route-result"><Badge level="LOW"/><b> Recommended Route: LOW FLOOD RISK</b><p>{route.route.join(' → ')}</p><div><strong>Distance</strong> {route.distanceKm} km · <strong>Travel time</strong> ~24 min</div><small>🔴 {route.avoidedAreas.join(' · 🟠 ')}</small></div>}</div><PuneMap predictions={data.predictions} segments={data.segments} nodes={data.nodes} horizon={horizon} layers={{rainfall:false,risk:true,network:true,critical:true}} route={route}/></section>; }

function App(){ const [data,setData]=useState(empty),[tab,setTab]=useState('Dashboard'),[horizon,setHorizon]=useState('60 minutes'),[layers,setLayers]=useState({rainfall:true,risk:true,network:true,critical:true}),[loading,setLoading]=useState(true),[intensity,setIntensity]=useState(40.3);
 const load=async(keepSelectedIntensity=false)=>{try{const paths=['rainfall','terrain','predictions','alerts','drainage/segments','drainage/nodes','simulation'];const r=await Promise.all(paths.map(p=>fetch(`${API}/${p}`).then(x=>x.json())));setData({rainfall:r[0],terrain:r[1],predictions:r[2],alerts:r[3],segments:r[4],nodes:r[5],simulation:r[6]});if(!keepSelectedIntensity)setIntensity(r[6]?.rainfallIntensity ?? 40.3);}catch(e){console.warn('Backend unavailable',e)}finally{setLoading(false)}};
 useEffect(()=>{load();const timer=setInterval(load,30000);return()=>clearInterval(timer)},[]);
 const changeRain=async value=>{const next=Number(value);setIntensity(next);try{await fetch(`${API}/simulation`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rainfallIntensity:next})});await load(true);}catch(e){console.warn('Simulation update failed',e)}};
 const current=data.predictions.filter(p=>p.horizon===(horizon==='CURRENT'?'30 minutes':horizon)); const high=current.filter(p=>p.riskLevel==='HIGH'||p.riskLevel==='SEVERE'); const latest=data.rainfall[0]; const active=tab==='Dashboard'; const nav=['Dashboard','Live Risk Map','Rainfall Monitoring','Drainage Monitoring','Flood Predictions','Alerts','Safe Route Planner'];
 return <div className="shell"><aside><div className="brand"><span>◈</span> NIRJAL</div><p>Urban flood nowcasting</p><div className="side-subtitle">Rainfall & Drainage Coupling Intelligence System</div><nav>{nav.map(item=><button key={item} onClick={()=>setTab(item)} className={tab===item?'selected':''}>{item}</button>)}</nav><div className="prototype">PROTOTYPE DATA<br/><small>Simulated / illustrative only</small></div></aside><main><header><div><p className="eyebrow">PUNE, MAHARASHTRA</p><h1>{tab}</h1></div><div className="live"><i/> LIVE SIMULATION <button onClick={load}>↻</button></div></header>{loading&&<div className="notice">Connecting to rainfall and drainage analysis…</div>}
 <section className="simulation panel"><div><p className="eyebrow">SIMULATION CONTROLS</p><h2>Rainfall Intensity <b>{Number(intensity).toFixed(1)} mm/hr</b></h2><small>Adjust the simulated rainfall to update runoff, drain load, overflow, flood zones and alerts.</small></div><input aria-label="Rainfall intensity" type="range" min="10" max="100" value={intensity} onChange={e=>changeRain(e.target.value)}/><div className="range-label"><span>10 mm/hr</span><span>100 mm/hr</span></div><div className="scenario-presets"><span>Demo scenario</span>{scenarios.map(s=><button key={s.name} className={Math.abs(Number(intensity)-s.value)<.2?'active':''} onClick={()=>changeRain(s.value)} title={s.detail}>{s.name}</button>)}<button className="reset" onClick={()=>changeRain(40.3)}>↺ Reset</button></div></section>
 {active&&<><section className="metrics"><Metric label="Current Rainfall" value={latest?`${latest.rainfallIntensity} mm/h`:'—'} sub={latest?.location||'Awaiting scenario data'}/><Metric label="High-Risk Areas" value={high.length} sub={`${horizons.find(x=>x.data===horizon)?.label} forecast`} accent="orange"/><Metric label="Critical Drains" value={data.segments.filter(s=>['CRITICAL','OVERFLOW'].includes(statusFromSegment(s))).length} sub="capacity threshold exceeded" accent="red"/><Metric label="Active Alerts" value={data.alerts.length} sub="requires monitoring" accent="yellow"/></section><Pipeline rainfall={data.rainfall} terrain={data.terrain} segments={data.segments} predictions={data.predictions}/><section className="grid"><div className="panel"><div className="panel-head"><h2>Live Flood Risk Map</h2><span>{horizon}</span></div><ForecastControls horizon={horizon} setHorizon={setHorizon}/><LayerToggles layers={layers} setLayers={setLayers}/><PuneMap predictions={data.predictions} segments={data.segments} nodes={data.nodes} horizon={horizon} layers={layers}/></div><div className="panel"><div className="panel-head"><h2>Active Flood Alerts</h2><button onClick={()=>setTab('Alerts')}>View all</button></div><Alerts alerts={data.alerts}/></div></section></>}
 {tab==='Live Risk Map'&&<section className="panel full"><div className="panel-head"><h2>Flood Risk Zones & Drainage Network</h2><span>Interactive Pune GIS layers</span></div><ForecastControls horizon={horizon} setHorizon={setHorizon}/><LayerToggles layers={layers} setLayers={setLayers}/><PuneMap predictions={data.predictions} segments={data.segments} nodes={data.nodes} horizon={horizon} layers={layers}/></section>}
 {tab==='Rainfall Monitoring'&&<Rainfall readings={data.rainfall}/>} {tab==='Drainage Monitoring'&&<Drainage rows={data.segments} full/>} {tab==='Flood Predictions'&&<Predictions predictions={data.predictions} horizon={horizon} setHorizon={setHorizon} full/>} {tab==='Alerts'&&<section className="panel full"><div className="panel-head"><h2>Incident Alerts</h2><span>Location-specific recommended actions</span></div><Alerts alerts={data.alerts}/></section>} {tab==='Safe Route Planner'&&<RoutePlanner data={data} horizon={horizon}/>} 
 <section className="how panel"><div><p className="eyebrow">ANALYSIS METHOD</p><h2>How it works</h2></div><ol><li>Rainfall intensity is analyzed.</li><li>Terrain influences surface runoff.</li><li>AI estimates expected runoff.</li><li>Drainage capacity is evaluated.</li><li>Hydraulic analysis detects bottlenecks.</li><li>Coupled nowcasting forecasts 0–3 hour flood risk.</li></ol></section>
 </main></div>; }
createRoot(document.getElementById('root')).render(<App/>);
