package com.sih.flood.service;

import com.sih.flood.dto.RainfallDto;
import com.sih.flood.dto.FloodDtos.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestClient;
import java.time.Instant;
import java.util.*;

/** In-memory synthetic prototype store; replace with JPA/PostGIS repositories in production. */
@Service public class FloodService {
 private final List<RainfallDto> rainfall = new ArrayList<>(); private final String aiBase; private volatile double simulatedRainfall=40.3;
 private final List<TerrainDto> terrain=List.of(new TerrainDto(1,"Shivajinagar",18.5308,73.8475,560,2.1,"low-lying urban",0.72),new TerrainDto(2,"Kothrud",18.5074,73.8077,574,4.5,"residential slope",0.36),new TerrainDto(3,"Hadapsar",18.5089,73.9260,555,1.4,"low-lying urban",0.80),new TerrainDto(4,"Katraj",18.4520,73.8650,620,7.0,"hilly",0.18),new TerrainDto(5,"Yerawada",18.5530,73.8780,552,1.7,"river plain",0.76));
 private final List<DrainNodeDto> nodes=List.of(new DrainNodeDto(1,"Mutha Outfall",18.532,73.855,552,0.68),new DrainNodeDto(2,"Shivajinagar Junction",18.531,73.847,559,0.82),new DrainNodeDto(3,"Hadapsar Culvert",18.509,73.926,554,0.91),new DrainNodeDto(4,"Yerawada Channel",18.553,73.878,551,0.88));
 private final List<DrainSegmentDto> segments=List.of(new DrainSegmentDto(1,"SC-01",2,1,940,1.2,3.8,3.0,"WARNING"),new DrainSegmentDto(2,"HC-07",3,1,2800,0.9,2.1,2.0,"WARNING"),new DrainSegmentDto(3,"YC-03",4,1,1700,0.8,1.7,1.65,"CRITICAL"));
 public FloodService(@Value("${ai.base-url}") String aiBase){this.aiBase=aiBase; seed();}
 private void seed(){ Instant now=Instant.now(); rainfall.addAll(List.of(new RainfallDto(1,"Shivajinagar",18.5308,73.8475,now.minusSeconds(1800),32.6,16.3),new RainfallDto(2,"Hadapsar",18.5089,73.9260,now.minusSeconds(1200),48.9,24.5),new RainfallDto(3,"Yerawada",18.5530,73.8780,now.minusSeconds(600),40.7,20.4),new RainfallDto(4,"Kothrud",18.5074,73.8077,now.minusSeconds(900),27.4,13.7),new RainfallDto(5,"Katraj",18.4520,73.8650,now.minusSeconds(1500),22.1,11.1))); }
 /** Smoothly varies the prototype feed so the dashboard has demonstrable live updates. */
 public List<RainfallDto> rainfall(){double pulse=1+Math.sin(System.currentTimeMillis()/30000d)*.04;double scale=simulatedRainfall/40.3;return rainfall.stream().map(r->new RainfallDto(r.id(),r.location(),r.latitude(),r.longitude(),r.timestamp(),round(r.rainfallIntensity()*scale*pulse),round(r.rainfallAmount()*scale*pulse))).sorted(Comparator.comparing(RainfallDto::timestamp).reversed()).toList();}
 public RainfallDto latest(){return rainfall().getFirst();}
 public RainfallDto add(RainfallDto input){var added=new RainfallDto(rainfall.size()+1,input.location(),input.latitude(),input.longitude(),input.timestamp()==null?Instant.now():input.timestamp(),input.rainfallIntensity(),input.rainfallAmount()); rainfall.add(added);return added;}
 public List<RainfallDto> rainfallAt(long id){var r=rainfall.stream().filter(x->x.id()==id).toList();if(r.isEmpty())throw new IllegalArgumentException("Rainfall location not found");return r;}
 public List<TerrainDto> terrain(){return terrain;} public List<DrainNodeDto> nodes(){return nodes;} public List<DrainSegmentDto> segments(){double flowMultiplier=.62+simulatedRainfall/100d;return segments.stream().map(s->{double flow=round(s.currentFlow()*flowMultiplier);double ratio=flow/s.capacity();String status=ratio>1?"OVERFLOW":ratio>.85?"CRITICAL":ratio>.70?"WARNING":"NORMAL";return new DrainSegmentDto(s.id(),s.name(),s.sourceNode(),s.destinationNode(),s.length(),s.diameter(),s.capacity(),flow,status);}).toList();}
 public SimulationDto simulation(){return new SimulationDto(simulatedRainfall);} public SimulationDto setSimulation(SimulationDto input){if(input.rainfallIntensity()<10||input.rainfallIntensity()>100)throw new IllegalArgumentException("Rainfall intensity must be between 10 and 100 mm/hr");simulatedRainfall=input.rainfallIntensity();return simulation();}
 private double runoff(double intensity, TerrainDto t){ try { @SuppressWarnings("unchecked") Map<String,Object> r=RestClient.create(aiBase).post().uri("/predict-runoff").body(Map.of("rainfall_intensity",intensity,"elevation",t.elevation(),"slope",t.slope(),"drainage_capacity",2.5)).retrieve().body(Map.class); return ((Number)r.get("expected_runoff")).doubleValue(); } catch(Exception ignored) { return Math.max(.1,intensity*.055*(1+(570-t.elevation())/400+t.slope()/25)); } }
 // EPA SWMM integration seam: replace this deterministic hydraulic approximation with a SWMM adapter.
 private Map<String,Double> simulateHydraulics(double runoff){ double cap=segments().stream().mapToDouble(DrainSegmentDto::capacity).sum(); double baseline=segments().stream().mapToDouble(DrainSegmentDto::currentFlow).sum(); double load=Math.min(1.5,(baseline+runoff)/cap); return Map.of("load",load,"overflow",Math.max(0,Math.min(1,(load-.72)/.45))); }
 public List<PredictionDto> predictions(){double rain=rainfall().stream().mapToDouble(RainfallDto::rainfallIntensity).average().orElse(0);int[] mins={30,60,120,180};List<PredictionDto> out=new ArrayList<>();for(TerrainDto t:terrain){ double run=runoff(rain,t); Map<String,Double> h=simulateHydraulics(run); for(int min:mins){double decay=1-(min-30)/700d;double low=Math.max(0,Math.min(1,(575-t.elevation())/30));double slope=Math.max(0,1-t.slope()/10);double score=Math.min(100,(rain/70*35+low*20+slope*10+h.get("load")*25+t.historicalRisk()*10)*decay);double overflow=Math.min(1,h.get("overflow")*decay+low*.12);double depth=Math.max(0,(score-32)*.72+overflow*16);out.add(new PredictionDto(min+" minutes",t.name(),t.latitude(),t.longitude(),level(score),round(score),round(depth),round(depth*.18),round(overflow*100),critical(h.get("load"))));}}return out;}
 private static String level(double s){return s<=25?"LOW":s<=50?"MODERATE":s<=75?"HIGH":"SEVERE";} private static double round(double d){return Math.round(d*10)/10d;} private List<String> critical(double load){return segments().stream().filter(s->s.currentFlow()/s.capacity()>0.78||load>.85).map(DrainSegmentDto::name).toList();}
 public List<AlertDto> alerts(){List<AlertDto> out=new ArrayList<>();long i=1;for(PredictionDto p:predictions())if((p.riskLevel().equals("HIGH")||p.riskLevel().equals("SEVERE"))&&p.horizon().equals("60 minutes")){String message=switch(p.location()){case "Shivajinagar"->"Predicted runoff is expected to exceed local drainage capacity within 1 hour.";case "Hadapsar"->"Water accumulation may reach "+p.waterDepthCm()+" cm if current rainfall intensity continues.";case "Yerawada"->"Drainage segment is approaching overflow threshold due to increasing runoff.";case "Kothrud"->"High surface runoff detected. Monitor low-lying road sections.";default->"Runoff and drainage load require monitoring in this zone.";};String action=p.riskLevel().equals("SEVERE")?"Deploy drainage response team and restrict waterlogged road access.":"Inspect nearby inlets and monitor the local drain load.";out.add(new AlertDto(i++,p.riskLevel(),p.location(),"1 Hour",message,p.waterDepthCm(),action));}return out;}
 public RouteDto route(RouteRequest r){if(r.source()==null||r.destination()==null)throw new IllegalArgumentException("Source and destination are required");List<String> path=List.of(r.source(),"Kothrud Safe Corridor","University Road",r.destination());return new RouteDto(path,10.8,List.of("Hadapsar Culvert high-risk zone","Yerawada Channel severe-risk zone"),"Prototype weighted graph route; high and severe zones receive prohibitive cost.");}
 public Map<String,Object> modelStatus(){try{return RestClient.create(aiBase).get().uri("/model-status").retrieve().body(Map.class);}catch(Exception e){return Map.of("model","backend explainable fallback","status","AI engine unavailable; local model active","training_data","synthetic prototype");}}
}
